// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'cross-env NODE_OPTIONS="--require ./scripts/dns-fix.cjs" tsx prisma/seed.ts',
  },
  // CLI-only (migrate/studio/db pull) — the app's runtime Prisma client
  // (lib/db/client.ts) builds its own PrismaPg adapter straight from
  // DATABASE_URL and never reads this file.
  //
  // Deliberately DATABASE_URL (the Supavisor pooler), not DIRECT_URL:
  // db.<ref>.supabase.co only has an AAAA record (no A record) unless the
  // project has Supabase's IPv4 add-on — confirmed via `nslookup -type=A`
  // returning nothing. Pointing this at DIRECT_URL makes every CLI command
  // fail with P1001 on any IPv4-only network. The pooler host is dual-stack
  // specifically to work around this, which is exactly why Supabase exposes
  // it in the first place. Note: @prisma/config@7.9.1's Datasource type
  // only has `url` and `shadowDatabaseUrl` — no `directUrl` field exists
  // despite some Prisma docs implying otherwise (verified against the
  // installed node_modules/@prisma/config/dist/index.d.ts), so there's no
  // way to give the CLI a different URL than the app runtime anyway.
  datasource: {
    url: env("DATABASE_URL"),
  },
});
